# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf60233bf8d4f66d358d5aa08d3975eed1b583ec2b8e538b4daf1a9f8c2d45ae1c6611f75a0d71fa5ebcbae6c98cd405969d1c45be4bddf365b14d7f7fc11031

test:
  secret_key_base: e9ab70accc03ce442ff56f306813f600fe945d3f64185cc1d4c92b773deea3f39c2e3e32a001bee0ad4043f6710de4b67273b7f506cade56a0a4440a33e1e21f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
